# -*- coding: utf-8 -*-
"""Agent_Workshop_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GIEe6tnrc8sU8qqhzxG9elNnWeag5PBv
"""

# MUST be first — before ANY other imports
import os
import re
os.environ["CREWAI_DISABLE_TELEMETRY"] = "true"
os.environ["OTEL_SDK_DISABLED"] = "true"

# Now safe to import everything else
import streamlit as st
from crew_setup import crew
from PIL import Image
import sys
import time
import glob

# ─────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────
def get_latest_image():
    files = glob.glob("diagram_*.png")
    if not files:
        return None
    return max(files, key=os.path.getctime)

def strip_ansi(text):
    """Remove ANSI terminal color/style escape codes."""
    return re.sub(r'\x1b\[[0-9;]*[mGKHF]', '', text)

def is_useful_log(line):
    """Filter out noisy CrewAI event bus warnings."""
    noise = [
        "CrewAIEventsBus",
        "Sync handler error",
        "Event pairing mismatch",
        "missing ScriptRunContext",
        "ScriptRunContext"
    ]
    return not any(n in line for n in noise)

# ─────────────────────────────────────────────
# PAGE CONFIG
# ─────────────────────────────────────────────
st.set_page_config(page_title="AI Content Studio", layout="wide")

st.title("🤖 AI Content Studio")
st.write("Generate AI explanations with diagrams using multi-agent collaboration.")

topic = st.text_input("Enter a topic", "Reinforcement Learning")

# ─────────────────────────────────────────────
# UI LAYOUT
# ─────────────────────────────────────────────
col1, col2 = st.columns([1, 2])

with col1:
    st.subheader("🧠 Agent Activity")
    log_box = st.empty()

with col2:
    st.subheader("📘 Explanation")
    result_container = st.empty()

diagram_container = st.container()

# ─────────────────────────────────────────────
# LOGGER — strips ANSI, filters noise, caps lines
# ─────────────────────────────────────────────
class StreamlitLogger:
    def __init__(self, container):
        self.container = container
        self.logs = []
        self.max_lines = 25

    def write(self, message):
        clean = strip_ansi(message.strip())
        if clean and is_useful_log(clean):
            self.logs.append(clean)
            display = "\n".join(self.logs[-self.max_lines:])
            self.container.code(display)

    def flush(self):
        pass

# ─────────────────────────────────────────────
# RUN BUTTON
# ─────────────────────────────────────────────
if st.button("Generate Content"):

    progress = st.progress(0)
    logger = StreamlitLogger(log_box)
    old_stdout = sys.stdout
    sys.stdout = logger

    try:
        progress.progress(10)
        print("🧠 Manager Agent: Planning task...")
        progress.progress(30)
        print("🔎 Research Agent: Retrieving knowledge...")

        result = crew.kickoff(inputs={"topic": topic})

        progress.progress(70)
        print("✏️ Reviewer Agent: Refining explanation...")
        progress.progress(85)
        print("🎨 Image Agent: Generating diagram...")
        progress.progress(100)

    finally:
        sys.stdout = old_stdout

    # ─────────────────────────────────────────────
    # SHOW EXPLANATION — extract clean text from CrewOutput
    # ─────────────────────────────────────────────
    result_text = result.raw if hasattr(result, 'raw') else str(result)

    # Remove diagram filename line from explanation box
    explanation_lines = [
        line for line in result_text.splitlines()
        if not line.strip().endswith(".png")
    ]
    explanation = "\n".join(explanation_lines).strip()
    result_container.markdown(explanation)

    # ─────────────────────────────────────────────
    # SHOW DIAGRAM
    # ─────────────────────────────────────────────
    with diagram_container:
        st.subheader("🖼 Diagram")
        latest_image = get_latest_image()
        if latest_image:
            image = Image.open(latest_image)
            st.image(image, use_container_width=True)
        else:
            st.warning("Diagram not found.")